[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pybites-carbon"
authors = [{name = "Bob Belderbos", email = "bob@pybit.es"}]
readme = "README.md"
requires-python = ">=3.7"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "pyperclip >=1.8.2",
    "python-dotenv >=0.19.0",
    "selenium >=3.141.0",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Documentation = "https://www.youtube.com/watch?v=oxeGhlJQll8"
Source = "https://github.com/bbelderbos/pybites-carbon"

[project.scripts]
carbon = "carbon.main:main"
